"""Pandera schema for city_of_pittsburgh / gis / pghwebcdbg2018blockgroups.

PGHWebCDBG2018Blockgroups

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "objectid_1": txt(),
        "objectid": txt(),
        "statefp10": txt(),
        "countyfp10": txt(),
        "tractce10": txt(),
        "blkgrpce10": txt(),
        "geoid10": txt(),
        "namelsad10": txt(),
        "mtfcc10": txt(),
        "funcstat10": txt(),
        "aland10": num(),
        "awater10": num(),
        "intptlat10": txt(),
        "intptlon10": txt(),
        "hood": txt(),
        "hood_no": num(),
        "acres": num(),
        "sqmiles": num(),
        "sectors": num(),
        "censusbloc": txt(),
        "hudtractnu": txt(),
        "st_area_sh": num(),
        "st_length_": num(),
        "cdbguogid2": num(),
        "cdbgname20": txt(),
        "stusab2018": txt(),
        "cdbgty2018": num(),
        "state2018": num(),
        "county2018": num(),
        "countyname": txt(),
        "tract2018": txt(),
        "blkgrp2018": num(),
        "lowmod2018": num(),
        "lowmoduniv": num(),
        "lowmodpct2": num(),
        "geoid2018": txt(),
        "cdbguogi_1": num(),
        "cdbgname_1": txt(),
        "stusab2014": txt(),
        "cdbgty2014": num(),
        "state2014": num(),
        "county2014": num(),
        "countyna_1": txt(),
        "tract2014": txt(),
        "blkgrp2014": num(),
        "lowmod2014": num(),
        "lowmodun_1": num(),
        "lowmodpc_1": num(),
        "geoid2014": txt(),
        "lmper2018": num(),
        "CDBG2018": txt(),
        "Shape__Area": num(),
        "Shape__Length": num(),
    }
)
