"""Pandera schema for allegheny_county / gis / park_features.

Allegheny County Park Features

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID": txt(),
        "UniCode": txt(),
        "Name": txt(),
        "Facility_Type": txt(),
        "TypeCode": num(),
        "Center": txt(),
        "CenterCode": txt(),
        "FeatureName": txt(),
        "Website": txt(),
        "Capacity": num(),
        "Access_to_Fire_Extinguisher": txt(),
        "Access_to_Kitchenette": txt(),
        "Access_to_Parking_Lot": txt(),
        "Access_to_Playground": txt(),
        "Access_to_Restrooms": txt(),
        "Access_to_Spray_Park": txt(),
        "Access_to_Vending_Machines": txt(),
        "ADA_Accessible_Facility": txt(),
        "ADA_Accessible_Playground__near": txt(),
        "ADA_Accessible_Port_A_John__nea": txt(),
        "ADA_Accessible_Restroom": txt(),
        "Bocci_Court": txt(),
        "Furniture__Chairs": txt(),
        "Furniture__Tables": txt(),
        "Indoor__Air_Conditioning": txt(),
        "Indoor__Audio_System": txt(),
        "Indoor__Heating": txt(),
        "Indoor__Television": txt(),
        "Outdoor__Basketball_Courts__nea": txt(),
        "Outdoor__Fishing": txt(),
        "Outdoor__Grill": txt(),
        "Outdoor__Horseshoe_Pits__near_": txt(),
        "Outdoor__Lake_View": txt(),
        "Outdoor__Lighting": txt(),
        "Outdoor__Swimming_Pool__near_": txt(),
        "Outdoor__VolleyBall": txt(),
        "Outdoor__Water_Spigot": txt(),
        "Outlet__Data": txt(),
        "Outlet__Power": txt(),
        "Outlet__Telephone": txt(),
        "Pet_Friendly": txt(),
        "Port_A_John__near_": txt(),
        "Smoking_Not_Permitted": txt(),
        "Smoking_Permitted": txt(),
        "X": num(),
        "Y": num(),
        "Resource_Type": txt(),
        "GlobalID": txt(),
    }
)
