"""Pandera schema for allegheny_county / gis / address_points.

Allegheny County Addressing Address Points

GENERATED by scripts/sync_pasda.py from the first
300 rows of the PASDA shapefile, so these are the ACTUAL
field names of the landed file — which is what schema_ok validates.

They are NOT the field names the layer's REST service reports: a
shapefile's DBF truncates field names to 10 characters, so the two
disagree. What lands is what matters here.

Types are conservative — txt() unless every sampled value parsed as a
number, and never for an identifier-shaped name. Tighten by hand:
  * mark the identifier key()
  * bound code domains with coded([...])
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "F_FEATURE_": txt(),
        "ADDRESS_ID": txt(),
        "PARENT_ID": txt(),
        "F_STREET_I": txt(),
        "F_DUP_STRE": txt(),
        "ADDRESS_TY": num(),
        "STATUS": txt(),
        "ADDR_NUM_P": txt(),
        "ADDR_NUM": num(),
        "ADDR_NUM_S": txt(),
        "ST_PREMODI": txt(),
        "ST_PREFIX": txt(),
        "ST_PRETYPE": txt(),
        "ST_NAME": txt(),
        "ST_TYPE": txt(),
        "ST_POSTMOD": txt(),
        "UNIT_TYPE": txt(),
        "UNIT": txt(),
        "FLOOR": txt(),
        "MUNICIPALI": txt(),
        "COUNTY": txt(),
        "STATE": txt(),
        "ZIP_CODE": txt(),
        "ZIP_CODE4": txt(),
        "COMMENT_": txt(),
        "EDIT_DATE": txt(),
        "EDIT_USER": txt(),
        "SOURCE": txt(),
        "EXP_FLAG": txt(),
        "FULL_ADDRE": txt(),
        "ENFORCE_VA": txt(),
        "SOURCE_ID": txt(),
        "ST_SUFFIX": txt(),
        "PARCELID": txt(),
    }
)
