"""Pandera schema for allegheny_county / gis / schools.

Allegheny County Schools

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID": txt(),
        "LEA_AUN": num(),
        "LEA_AIU_Description": txt(),
        "LEA_Inst_Name": txt(),
        "School_Name": txt(),
        "City": txt(),
        "State": txt(),
        "Zipcode": txt(),
        "Full_Address": txt(),
        "Grade_List": txt(),
        "Elementary": num(),
        "Secondary": num(),
        "Grade_K": num(),
        "Grade_1": num(),
        "Grade_2": num(),
        "Grade_3": num(),
        "Grade_4": num(),
        "Grade_5": num(),
        "Grade_6": num(),
        "Grade_7": num(),
        "Grade_8": num(),
        "Grade_9": num(),
        "Grade_10": num(),
        "Grade_11": num(),
        "Grade_12": num(),
        "Cyber_School": txt(),
        "Last_Edit_Date": txt(),
        "School_Category": txt(),
        "School_Category_Description": txt(),
        "Address": txt(),
    }
)
