"""Pandera schema for allegheny_county / gis / addressing_landmarks.

Allegheny County Addressing Landmarks

GENERATED by scripts/sync_arcgis.py by sampling the real CSV
export (first 2000 rows / 2048KiB). This layer is a
plain TABLE with no geometry, so the CSV is the landed file and
these are its ACTUAL headers — which is what schema_ok validates,
since it runs pre-transform. Nor are these the legacy rocket-etl
`load_from` names: that engine lowercased every header before
matching, so its spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID": txt(),
        "ADDRESS_ID": txt(),
        "LANDMARK": txt(),
        "GlobalID": txt(),
        "CLASS": num(),
        "TYPE": txt(),
        "PUB": txt(),
    }
)
