"""Pandera schema for allegheny_county / gis / beltway_centerlines.

Allegheny County Beltway System Street Centerlines

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "FID": txt(),
        "PREFIX": txt(),
        "NAME": txt(),
        "TYPE": txt(),
        "SUFFIX": txt(),
        "STREETNAME": txt(),
        "ALTERNATEN": txt(),
        "LLEFT": num(),
        "HLEFT": num(),
        "LRGT": num(),
        "HRGT": num(),
        "FROMSTREET": txt(),
        "TOSTREET": txt(),
        "ZIPL": num(),
        "ZIPR": num(),
        "MCDL": num(),
        "MCDR": num(),
        "OWNER": txt(),
        "BELTWAY": txt(),
        "MAJORRD": txt(),
        "NO_LANES": num(),
        "CFCC": txt(),
        "GDTLINK": txt(),
        "ONEWAY": txt(),
        "UNIQUE_ID": txt(),
        "ROUTE_NO": txt(),
        "SYSTEMID": num(),
        "USERID": num(),
        "FEATURECOD": num(),
        "UPDATE_YEA": num(),
        "MODIFIEDBY": txt(),
        "MODIFIEDON": txt(),
        "CREATEDBY": txt(),
        "CREATEDON": txt(),
        "Shape_Leng": num(),
    }
)
