"""Pandera schema for city_of_pittsburgh / gis / pghwebrco.

PGHWebRCO

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID_1": txt(),
        "objectid": txt(),
        "organization_name": txt(),
        "rco_approval_date": txt(),
        "rco_expiration_date": txt(),
        "organization_address": txt(),
        "meeting_location_address": txt(),
        "meeting_dates__and_times": txt(),
        "website": txt(),
        "primary_contact_name": txt(),
        "primary_contact_mailing_address": txt(),
        "primary_contact_email": txt(),
        "primary_contact_phone": txt(),
        "primary_contact_phone_ext": txt(),
        "alternate_contact_name": txt(),
        "alternate_contact_mailing_addre": txt(),
        "alternate_contact_email": txt(),
        "alternate_contact_phone": txt(),
        "alternate_contact_phone_ext": txt(),
        "third_contact_name": txt(),
        "third_contact_email": txt(),
        "Shape__Area": num(),
        "Shape__Length": num(),
    }
)
