"""Pandera schema for city_of_pittsburgh / gis / neighborhoods.

Neighborhoods

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID": txt(),
        "fid_blockg": txt(),
        "statefp10": txt(),
        "countyfp10": txt(),
        "tractce10": txt(),
        "blkgrpce10": txt(),
        "geoid10": txt(),
        "namelsad10": txt(),
        "mtfcc10": txt(),
        "funcstat10": txt(),
        "aland10": num(),
        "awater10": num(),
        "intptlat10": txt(),
        "intptlon10": txt(),
        "shape_leng": num(),
        "fid_neighb": txt(),
        "perimeter": num(),
        "neighbor_": num(),
        "neighbor_i": num(),
        "hood": txt(),
        "hood_no": num(),
        "acres": num(),
        "sqmiles": num(),
        "dpwdiv": num(),
        "unique_id": txt(),
        "sectors": num(),
        "shape_le_1": num(),
        "shape_ar_1": num(),
        "page_number": num(),
        "plannerassign": txt(),
        "created_user": txt(),
        "created_date": txt(),
        "last_edited_user": txt(),
        "last_edited_date": txt(),
        "temp": txt(),
        "pghdb_sde_Neighborhood_2010_are": num(),
        "GlobalID": txt(),
        "Shape__Area": num(),
        "Shape__Length": num(),
    }
)
