"""Pandera schema for city_of_pittsburgh / gis / steps.

Pittsburgh Steps

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "objectid": txt(),
        "length": num(),
        "streets_": num(),
        "streets_id": txt(),
        "code": txt(),
        "type": num(),
        "id_no": txt(),
        "oid": txt(),
        "id": txt(),
        "dpwn1": num(),
        "dpwn2": num(),
        "location": txt(),
        "style": num(),
        "angle": txt(),
        "segs": num(),
        "st_": txt(),
        "street_nam": txt(),
        "from_stree": txt(),
        "to_street": txt(),
        "int_": txt(),
        "hood": num(),
        "hood2": num(),
        "l_feet": num(),
        "width": num(),
        "steps": num(),
        "treads": num(),
        "year": num(),
        "coded_": txt(),
        "pix": txt(),
        "comment": txt(),
        "Shape__Length": num(),
    }
)
