"""Pandera schema for city_of_pittsburgh / gis / inclusionaryhousingoverlaydistrict.

InclusionaryHousingOverlayDistrict

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID_1": txt(),
        "OBJECTID": txt(),
        "FID_BlockG": txt(),
        "STATEFP10": txt(),
        "COUNTYFP10": txt(),
        "TRACTCE10": txt(),
        "BLKGRPCE10": txt(),
        "GEOID10": txt(),
        "NAMELSAD10": txt(),
        "MTFCC10": txt(),
        "FUNCSTAT10": txt(),
        "ALAND10": num(),
        "AWATER10": num(),
        "INTPTLAT10": txt(),
        "INTPTLON10": txt(),
        "Shape_Leng": num(),
        "FID_Neighb": txt(),
        "AREA": num(),
        "PERIMETER": num(),
        "NEIGHBOR_": num(),
        "NEIGHBOR_I": num(),
        "HOOD": txt(),
        "HOOD_NO": num(),
        "ACRES": num(),
        "SQMILES": num(),
        "DPWDIV": num(),
        "UNIQUE_ID": txt(),
        "SECTORS": num(),
        "Shape_Le_1": num(),
        "Shape_Ar_1": num(),
        "Page_Numbe": num(),
        "Shape_Le_2": num(),
        "CENTROID_X": num(),
        "CENTROID_Y": num(),
        "Shape__Area": num(),
        "Shape__Length": num(),
    }
)
