"""Pandera schema for city_of_pittsburgh / gis / street_centerline.

Pittsburgh Street Centerline

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID_1": txt(),
        "objectid_2": txt(),
        "objectid": txt(),
        "length": num(),
        "streetcl_i": num(),
        "prefix": txt(),
        "name": txt(),
        "type": txt(),
        "suffix": txt(),
        "dir": txt(),
        "streetname": txt(),
        "alternaten": txt(),
        "lleft": num(),
        "hleft": num(),
        "lrgt": num(),
        "hrgt": num(),
        "fromstreet": txt(),
        "tostreet": txt(),
        "zipl": num(),
        "zipr": num(),
        "mcdl": num(),
        "mcdr": num(),
        "owner": txt(),
        "beltway": txt(),
        "majorrd": txt(),
        "no_lanes": num(),
        "cfcc": txt(),
        "gdtlink": txt(),
        "oneway": txt(),
        "stcl_code": txt(),
        "unique_id": txt(),
        "route_no": txt(),
        "std_rng": txt(),
        "cltype": txt(),
        "halfvac": txt(),
        "cen20lt": num(),
        "cen20rg": num(),
        "zone_left": txt(),
        "zone_right": txt(),
        "hood_left": txt(),
        "hood_right": txt(),
        "dpw_zon_lt": num(),
        "dpw_zon_rt": num(),
        "fire_zn_lt": txt(),
        "fire_zn_rt": txt(),
        "ward_lt": txt(),
        "ward_rg": txt(),
        "nh_l": num(),
        "nh_r": num(),
        "council_lt": num(),
        "council_rt": num(),
        "vote_dt_lt": num(),
        "vote_dt_rt": num(),
        "class": txt(),
        "paveddate": txt(),
        "strtfromto": txt(),
        "measurlgth": num(),
        "roadwidth": num(),
        "cdbg": txt(),
        "roadclass": txt(),
        "paveclass": txt(),
        "segpavclas": txt(),
        "segname": txt(),
        "pghdb_sde_Pavement_len": num(),
        "uniqueidse": num(),
        "shape_leng": num(),
        "carteid": num(),
        "cen2010lt": txt(),
        "cen2010rg": txt(),
        "council201": num(),
        "council2_1": num(),
        "saltroute": txt(),
        "saltrte": txt(),
        "test": num(),
        "cwsaltrte": txt(),
        "saltrtediv": txt(),
        "retired": txt(),
        "areasqft": num(),
        "rsroadclas": txt(),
        "rsleft_not": txt(),
        "rsright_no": txt(),
        "rsft_penal": num(),
        "rstf_penal": num(),
        "rsfromutur": txt(),
        "rstouturnr": txt(),
        "rsleftno_l": num(),
        "rsrightno_": num(),
        "rsclass": txt(),
        "created_user": txt(),
        "created_date": txt(),
        "last_edited_user": txt(),
        "last_edited_date": txt(),
        "sweep_left": txt(),
        "sweep_right": txt(),
        "estimatedoci": num(),
        "olddpw_div_l": num(),
        "olddpw_div_r": num(),
        "bikelanetype1": txt(),
        "bikelanetype2": txt(),
        "bikelaneinstalled": txt(),
        "speedlimit": num(),
        "num_lanes": num(),
        "class_snow": txt(),
        "snowresponse": txt(),
        "replaced": txt(),
        "truckroutes": txt(),
        "route_type": txt(),
        "route_num": num(),
        "roadclosure": txt(),
        "roadclosure_fromdate": txt(),
        "roadclosure_todate": txt(),
        "update_es": txt(),
        "update_sr": txt(),
        "update_addr": txt(),
        "domi_class": txt(),
        "GlobalID": txt(),
        "future_pave_date": txt(),
        "paser_score": num(),
        "Shape__Length": num(),
    }
)
