"""Pandera schema for city_of_pittsburgh / gis / greenways.

Greenways

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID_1": txt(),
        "objectid": txt(),
        "perimeter": num(),
        "greenway_": num(),
        "greenway_i": num(),
        "name": txt(),
        "acres": num(),
        "sqmiles": num(),
        "nhood": txt(),
        "dpwdiv": num(),
        "shape_leng": num(),
        "date_resol": txt(),
        "label": txt(),
        "cartid": txt(),
        "created_user": txt(),
        "created_date": txt(),
        "last_edited_user": txt(),
        "last_edited_date": txt(),
        "pghdb_sde_greenwayscartegraph_a": num(),
        "GlobalID": txt(),
        "Shape__Area": num(),
        "Shape__Length": num(),
    }
)
