"""Pandera schema for allegheny_county / gis / community_need_index.

Allegheny County Community Need Index (used in 2024 report)

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID_1": txt(),
        "STATEFP20": txt(),
        "COUNTYFP20": txt(),
        "TRACTCE20": txt(),
        "GEOID20": txt(),
        "NAME20": num(),
        "NAMELSAD20": txt(),
        "MTFCC20": txt(),
        "FUNCSTAT20": txt(),
        "ALAND20": num(),
        "AWATER20": num(),
        "INTPTLAT20": txt(),
        "INTPTLON20": txt(),
        "GEOIDFORJO": txt(),
        "OBJECTID": txt(),
        "GEO_ID_LONG": txt(),
        "GEO_ID_SHORT": txt(),
        "TRACT_NAME": txt(),
        "MUNI": txt(),
        "PGH_NHOOD": txt(),
        "MUNI_TYPE": txt(),
        "EXCLUDE_": num(),
        "TOTAL_POP": num(),
        "HISPANIC_LATINO": num(),
        "WHITE_ALONE": num(),
        "BLACK_ALONE": num(),
        "INDIGENIOUS_ALONE": num(),
        "ASIAN_PI_ALONE": num(),
        "OTHER": num(),
        "MULTIRACIAL": num(),
        "Percent_CollegeorMore_Enrollmen": num(),
        "Significant_College_Enrollment": num(),
        "FamPovRate": num(),
        "MaleUnemploymentJoblessnessRate": num(),
        "MaleUnemploymentJoblessnessRa_1": num(),
        "AdjustedMaleUnemploymentJobless": num(),
        "Rate25UpwoBachelorsOrMore": num(),
        "SingleParentRate": num(),
        "Avg_Hom_Rate": num(),
        "Avg_Fatal_Overdose_Rate": num(),
        "PercentwoInternet": num(),
        "NoVehicleRate": num(),
        "RenterNoVehicleRent": num(),
        "Rate_of_Suicide_Victims_RES": num(),
        "FamWhiteBelowFPL": num(),
        "FamBlackBelowFPL": num(),
        "FamNABelowFPL": num(),
        "FamAsianPIBelowFPL": num(),
        "FamOtherBelowFPL": num(),
        "FamMultiRaceBelowFPL": num(),
        "FamLatinoBelowFPL": num(),
        "FamWhiteNotLatinoBelowFPL": num(),
        "FamWhiteAboveFPL": num(),
        "FamBlackAboveFPL": num(),
        "FamNAAboveFPL": num(),
        "FamAsianPIAboveFPL": num(),
        "FamOtherAboveFPL": num(),
        "FamMultiRaceAboveFPL": num(),
        "FamLatinoAboveFPL": num(),
        "FamWhiteNotLatinoAboveFPL": num(),
        "MedianHomeValue": txt(),
        "MedianGrossRent": num(),
        "MedianIncome": num(),
        "AvgAdultIncomeOutcomeforLow_inc": num(),
        "JunkCount": num(),
        "PercentHispanicLatino": num(),
        "PercentWhite": num(),
        "PercentBlack": num(),
        "PercentIndigenious": num(),
        "PercentAsianPI": num(),
        "PercentOther": num(),
        "PercentMultiRacial": num(),
        "ZScore_20225YE_FamPovRate": num(),
        "ZScore_20225YE_UnemployJoblessR": num(),
        "ZScore_20225YE_NoCollegeAttRate": num(),
        "ZScore_20225YE_SingleParentRate": num(),
        "ZScore_20225YE_AvgHomRate": num(),
        "ZScore_20225YE_FatalOvdRate": num(),
        "ZScore_20225YE_NoInternetRate": num(),
        "ZScore_20225YE_NoVehicleRate": num(),
        "AverageZScore_20225YE": num(),
        "LevelofNeed_20225YE": txt(),
        "LevelofNeed_Grouping_20225YE": txt(),
        "PercentNonWhite": num(),
        "PerPOC_Class2020": txt(),
        "PerBlackClass2020": txt(),
        "LevelofNeed_SORT": num(),
        "FamPovRate2017": num(),
        "AdjustedMaleUnemploymentJoble_1": num(),
        "Rate25UpwoBachelorsOrMore2017": num(),
        "SingleParentRate2017": num(),
        "Avg_Hom_Rate2017": num(),
        "Avg_Fatal_Overdose_Rate2017": num(),
        "PercentwoInternet2017": num(),
        "NoVehicleRate2017": num(),
        "LevelofNeed_20175YE": txt(),
        "NeedOvertime": txt(),
        "NeedOvertime_SORT": num(),
        "Shape__Area": num(),
        "Shape__Length": num(),
    }
)
