"""Pandera schema for city_of_pittsburgh / gis / justice40_neighborhoods.

Justice40 Neighborhoods

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "OBJECTID": txt(),
        "GEOID10": txt(),
        "SF": txt(),
        "CF": txt(),
        "DF_PFS": num(),
        "AF_PFS": num(),
        "HDF_PFS": num(),
        "DSF_PFS": num(),
        "EBF_PFS": num(),
        "EALR_PFS": num(),
        "EBLR_PFS": num(),
        "EPLR_PFS": num(),
        "HBF_PFS": num(),
        "LLEF_PFS": num(),
        "LIF_PFS": num(),
        "LMI_PFS": num(),
        "PM25F_PFS": num(),
        "HSEF": num(),
        "P100_PFS": num(),
        "P200_I_PFS": num(),
        "AJDLI_ET": num(),
        "LPF_PFS": num(),
        "KP_PFS": num(),
        "NPL_PFS": num(),
        "RMP_PFS": num(),
        "TSDF_PFS": num(),
        "TPF": num(),
        "TF_PFS": num(),
        "UF_PFS": num(),
        "WF_PFS": num(),
        "UST_PFS": num(),
        "N_WTR": num(),
        "N_WKFC": num(),
        "N_CLT": num(),
        "N_ENY": num(),
        "N_TRN": num(),
        "N_HSG": num(),
        "N_PLN": num(),
        "N_HLTH": num(),
        "SN_C": num(),
        "SN_T": txt(),
        "DLI": num(),
        "ALI": num(),
        "PLHSE": num(),
        "LMILHSE": num(),
        "ULHSE": num(),
        "EPL_ET": num(),
        "EAL_ET": num(),
        "EBL_ET": num(),
        "EB_ET": num(),
        "PM25_ET": num(),
        "DS_ET": num(),
        "TP_ET": num(),
        "LPP_ET": num(),
        "HRS_ET": num(),
        "KP_ET": num(),
        "HB_ET": num(),
        "RMP_ET": num(),
        "NPL_ET": num(),
        "TSDF_ET": num(),
        "WD_ET": num(),
        "UST_ET": num(),
        "DB_ET": num(),
        "A_ET": num(),
        "HD_ET": num(),
        "LLE_ET": num(),
        "UN_ET": num(),
        "LISO_ET": num(),
        "POV_ET": num(),
        "LMI_ET": num(),
        "IA_LMI_ET": num(),
        "IA_UN_ET": num(),
        "IA_POV_ET": num(),
        "TC": num(),
        "CC": num(),
        "IAULHSE": num(),
        "IAPLHSE": num(),
        "IALMILHSE": num(),
        "IALMIL_76": num(),
        "IAPLHS_77": num(),
        "IAULHS_78": num(),
        "LHE": num(),
        "IALHE": num(),
        "IAHSEF": num(),
        "N_CLT_EOMI": num(),
        "N_ENY_EOMI": num(),
        "N_TRN_EOMI": num(),
        "N_HSG_EOMI": num(),
        "N_PLN_EOMI": num(),
        "N_WTR_EOMI": num(),
        "N_HLTH_88": num(),
        "N_WKFC_89": num(),
        "FPL200S": num(),
        "N_WKFC_91": num(),
        "TD_ET": num(),
        "TD_PFS": num(),
        "FLD_PFS": num(),
        "WFR_PFS": num(),
        "FLD_ET": num(),
        "WFR_ET": num(),
        "ADJ_ET": num(),
        "IS_PFS": num(),
        "IS_ET": num(),
        "AML_ET": num(),
        "FUDS_RAW": num(),
        "FUDS_ET": num(),
        "IMP_FLG": num(),
        "DM_B": num(),
        "DM_AI": num(),
        "DM_A": num(),
        "DM_HI": num(),
        "DM_T": num(),
        "DM_W": num(),
        "DM_H": num(),
        "DM_O": num(),
        "AGE_10": num(),
        "AGE_MIDDLE": num(),
        "AGE_OLD": num(),
        "TA_COU_116": num(),
        "TA_COUNT_C": num(),
        "TA_PERC": num(),
        "TA_PERC_FE": num(),
        "UI_EXP": txt(),
        "THRHLD": num(),
        "Shape__Area": num(),
        "Shape__Length": num(),
    }
)
