"""Pandera schema for allegheny_county / gis / pa_house_districts.

Allegheny County PA House Districts

GENERATED by scripts/sync_arcgis.py by sampling the real GeoJSON
export (first 200 features / 2048KiB), so these are the ACTUAL
feature properties of the landed file — which is what schema_ok
validates, since it runs pre-transform.

Do NOT reconcile these against the CSV export: it is a DIFFERENT
column set, not the same data without geometry. The GeoJSON of
municipal_boundaries has 19 properties against the CSV's 21 columns,
and county_boundary spells the same field COUNTYFIPS where the CSV
says `County FIPS`. Nor are these the legacy rocket-etl `load_from`
names: that engine lowercased every header before matching, so its
spellings are not evidence of the real casing.

Types are conservative — txt() unless every sampled value parsed as a
number. Tighten by hand against the data dictionary:
  * mark the identifier key()
  * bound code domains with coded([...])
  * ge0() / ranged(lo, hi) where the range is known
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "FID": txt(),
        "ID": txt(),
        "AREA": num(),
        "DISTRICT": txt(),
        "MEMBERS": num(),
        "LOCKED": txt(),
        "NAME": txt(),
        "ADJ_POPULA": num(),
        "ADJ_NH_WHT": num(),
        "ADJ_NH_BLK": num(),
        "ADJ_NH_IND": num(),
        "ADJ_NH_ASN": num(),
        "ADJ_NH_HWN": num(),
        "ADJ_NH_OTH": num(),
        "ADJ_NH_2_R": num(),
        "ADJ_HISPAN": num(),
        "ADJ_18_POP": num(),
        "ADJ_NH18_W": num(),
        "ADJ_NH18_B": num(),
        "ADJ_NH18_I": num(),
        "ADJ_NH18_A": num(),
        "ADJ_NH18_H": num(),
        "ADJ_NH18_O": num(),
        "ADJ_NH18_2": num(),
        "ADJ_H18_PO": num(),
        "IDEAL_VALU": num(),
        "DEVIATION": num(),
        "F_DEVIATIO": num(),
        "ALTERNATE_": num(),
        "POLSBY_POP": num(),
        "F_ADJ_NH_W": num(),
        "F_ADJ_NH_B": num(),
        "F_ADJ_NH_I": num(),
        "F_ADJ_NH_A": num(),
        "F_ADJ_NH_H": num(),
        "F_ADJ_NH_O": num(),
        "F_ADJ_NH_2": num(),
        "F_ADJ_HISP": num(),
        "F_ADJ_NH18": num(),
        "F_ADJ_NH11": num(),
        "F_ADJ_NH12": num(),
        "F_ADJ_NH13": num(),
        "F_ADJ_NH14": num(),
        "F_ADJ_NH15": num(),
        "F_ADJ_NH16": num(),
        "F_ADJ_H18_": num(),
        "DISTRICT_N": txt(),
        "DISTRICT_L": txt(),
    }
)
