"""Pandera schema for allegheny_county / gis / street_centerlines.

Allegheny County Addressing Street Centerlines

GENERATED by scripts/sync_pasda.py from the first
300 rows of the PASDA shapefile, so these are the ACTUAL
field names of the landed file — which is what schema_ok validates.

They are NOT the field names the layer's REST service reports: a
shapefile's DBF truncates field names to 10 characters, so the two
disagree. What lands is what matters here.

Types are conservative — txt() unless every sampled value parsed as a
number, and never for an identifier-shaped name. Tighten by hand:
  * mark the identifier key()
  * bound code domains with coded([...])
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "FEATURE_KE": txt(),
        "L_STREET_I": txt(),
        "R_STREET_I": txt(),
        "L_DUP_STRE": txt(),
        "R_DUP_STRE": txt(),
        "CAD_LLO": num(),
        "CAD_LHI": num(),
        "CAD_RLO": num(),
        "CAD_RHI": num(),
        "LLO": num(),
        "LHI": num(),
        "RLO": num(),
        "RHI": num(),
        "ST_PREMODI": txt(),
        "ST_PREFIX": txt(),
        "ST_PRETYPE": txt(),
        "ST_NAME": txt(),
        "ST_TYPE": txt(),
        "ST_POSTMOD": txt(),
        "LMUNI": txt(),
        "RMUNI": txt(),
        "LCOUNTY": txt(),
        "RCOUNTY": txt(),
        "LSTATE": txt(),
        "RSTATE": txt(),
        "L_ZIP": txt(),
        "R_ZIP": txt(),
        "EDIT_DATE": txt(),
        "EDIT_USER": txt(),
        "F_NODE": txt(),
        "T_NODE": txt(),
        "FCC": txt(),
        "SPEED": num(),
        "F_ZLEV": num(),
        "T_ZLEV": num(),
        "ONEWAY": txt(),
        "LAR": txt(),
        "LARDIR": txt(),
        "A1": txt(),
        "A2": txt(),
        "DYNAMAPID": txt(),
        "FULL_NAME": txt(),
        "CADA2": txt(),
        "CADA1": txt(),
        "P_OVR_L": txt(),
        "P_OVR_R": txt(),
        "F_OVR_L": txt(),
        "F_OVR_R": txt(),
        "E_OVR_L": txt(),
        "E_OVR_R": txt(),
        "CAD2": txt(),
        "ENFORCE_VA": txt(),
        "SOURCE_ID": txt(),
        "ST_SUFFIX": txt(),
        "Global_ID": txt(),
        "COMMENTS": txt(),
        "SOURCE": txt(),
        "Shape_Leng": num(),
    }
)
