"""Pandera schema for allegheny_county / gis / parcels.

Allegheny County Parcel Boundaries

GENERATED by scripts/sync_pasda.py from the first
300 rows of the PASDA shapefile, so these are the ACTUAL
field names of the landed file — which is what schema_ok validates.

They are NOT the field names the layer's REST service reports: a
shapefile's DBF truncates field names to 10 characters, so the two
disagree. What lands is what matters here.

Types are conservative — txt() unless every sampled value parsed as a
number, and never for an identifier-shaped name. Tighten by hand:
  * mark the identifier key()
  * bound code domains with coded([...])
Do NOT add reverse-geocoded or otherwise derived columns here.
"""

from __future__ import annotations

from wprdc_etl.strategies.schema import frame, num, txt

SCHEMA = frame(
    {
        "PIN": txt(),
        "MAPBLOCKLO": txt(),
        "MUNICODE": txt(),
        "CALCACREAG": num(),
        "NOTES": txt(),
        "PSEUDONO": txt(),
        "COMMENTS": txt(),
        "GlobalID": txt(),
        "Shape_Leng": num(),
        "Shape_Area": num(),
    }
)
